//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

/* eslint-disable */
/* jshint ignore: start */

(function(module, require, exports)
{
    const Ice = require("ice").Ice;
    const _ModuleRegistry = Ice._ModuleRegistry;
    const Slice = Ice.Slice;

    let Chat = _ModuleRegistry.module("Chat");

    Chat.MessageTypeEnum = Slice.defineEnum([
        ['TEXT', 0], ['SYSTEM', 1], ['AUDIO', 2], ['VOICECALL', 3]]);

    Chat.MessageDTO = class
    {
        constructor(id = "", senderId = "", senderName = "", content = "", timestamp = new Ice.Long(0, 0), type = Chat.MessageTypeEnum.TEXT)
        {
            this.id = id;
            this.senderId = senderId;
            this.senderName = senderName;
            this.content = content;
            this.timestamp = timestamp;
            this.type = type;
        }

        _write(ostr)
        {
            ostr.writeString(this.id);
            ostr.writeString(this.senderId);
            ostr.writeString(this.senderName);
            ostr.writeString(this.content);
            ostr.writeLong(this.timestamp);
            Chat.MessageTypeEnum._write(ostr, this.type);
        }

        _read(istr)
        {
            this.id = istr.readString();
            this.senderId = istr.readString();
            this.senderName = istr.readString();
            this.content = istr.readString();
            this.timestamp = istr.readLong();
            this.type = Chat.MessageTypeEnum._read(istr);
        }

        static get minWireSize()
        {
            return  13;
        }
    };

    Slice.defineStruct(Chat.MessageDTO, true, true);

    Chat.UserDTO = class
    {
        constructor(id = "", username = "", isOnline = false, connectedAt = new Ice.Long(0, 0))
        {
            this.id = id;
            this.username = username;
            this.isOnline = isOnline;
            this.connectedAt = connectedAt;
        }

        _write(ostr)
        {
            ostr.writeString(this.id);
            ostr.writeString(this.username);
            ostr.writeBool(this.isOnline);
            ostr.writeLong(this.connectedAt);
        }

        _read(istr)
        {
            this.id = istr.readString();
            this.username = istr.readString();
            this.isOnline = istr.readBool();
            this.connectedAt = istr.readLong();
        }

        static get minWireSize()
        {
            return  11;
        }
    };

    Slice.defineStruct(Chat.UserDTO, true, true);

    Slice.defineSequence(Chat, "StringListHelper", "Ice.StringHelper", false);

    Chat.GroupDTO = class
    {
        constructor(id = "", name = "", memberIds = null)
        {
            this.id = id;
            this.name = name;
            this.memberIds = memberIds;
        }

        _write(ostr)
        {
            ostr.writeString(this.id);
            ostr.writeString(this.name);
            Chat.StringListHelper.write(ostr, this.memberIds);
        }

        _read(istr)
        {
            this.id = istr.readString();
            this.name = istr.readString();
            this.memberIds = Chat.StringListHelper.read(istr);
        }

        static get minWireSize()
        {
            return  3;
        }
    };

    Slice.defineStruct(Chat.GroupDTO, true, true);

    Slice.defineSequence(Chat, "MessageListHelper", "Chat.MessageDTO", false);

    Slice.defineSequence(Chat, "UserListHelper", "Chat.UserDTO", false);

    Slice.defineSequence(Chat, "GroupListHelper", "Chat.GroupDTO", false);

    const iceC_Chat_Observer_ids = [
        "::Chat::Observer",
        "::Ice::Object"
    ];

    Chat.Observer = class extends Ice.Object
    {
    };

    Chat.ObserverPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Chat.Observer, Chat.ObserverPrx, iceC_Chat_Observer_ids, 0,
    {
        "updateMessages": [, , , , , [["Chat.MessageListHelper"]], , , , ],
        "updateUsers": [, , , , , [["Chat.UserListHelper"]], , , , ]
    });

    const iceC_Chat_Subject_ids = [
        "::Chat::Subject",
        "::Ice::Object"
    ];

    Chat.Subject = class extends Ice.Object
    {
    };

    Chat.SubjectPrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Chat.Subject, Chat.SubjectPrx, iceC_Chat_Subject_ids, 0,
    {
        "attachObserver": [, , , , , [["Chat.ObserverPrx"]], , , , ],
        "detachObserver": [, , , , , [["Chat.ObserverPrx"]], , , , ]
    });

    const iceC_Chat_ChatService_ids = [
        "::Chat::ChatService",
        "::Ice::Object"
    ];

    Chat.ChatService = class extends Ice.Object
    {
    };

    Chat.ChatServicePrx = class extends Ice.ObjectPrx
    {
    };

    Slice.defineOperations(Chat.ChatService, Chat.ChatServicePrx, iceC_Chat_ChatService_ids, 0,
    {
        "joinChat": [, , , , [Chat.UserDTO], [[7]], , , , ],
        "leaveChat": [, , , , , [[7]], , , , ],
        "getUsers": [, , , , ["Chat.UserListHelper"], , , , , ],
        "sendMessage": [, , , , , [[7], [7], [Chat.MessageTypeEnum._helper]], , , , ],
        "getMessages": [, , , , ["Chat.MessageListHelper"], , , , , ],
        "sendPrivateMessage": [, , , , , [[7], [7], [7], [Chat.MessageTypeEnum._helper]], , , , ],
        "getPrivateMessages": [, , , , ["Chat.MessageListHelper"], [[7], [7]], , , , ],
        "createGroup": [, , , , [Chat.GroupDTO], [[7], [7]], , , , ],
        "joinGroup": [, , , , , [[7], [7]], , , , ],
        "getGroups": [, , , , ["Chat.GroupListHelper"], , , , , ],
        "startVoiceCall": [, , , , , [[7], [7]], , , , ],
        "endVoiceCall": [, , , , , [[7]], , , , ],
        "sendGroupMessage": [, , , , , [[7], [7], [7], [Chat.MessageTypeEnum._helper]], , , , ],
        "getGroupMessages": [, , , , ["Chat.MessageListHelper"], [[7]], , , , ]
    });
    exports.Chat = Chat;
}
(typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? module : undefined,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? require :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self.Ice._require : window.Ice._require,
 typeof(global) !== "undefined" && typeof(global.process) !== "undefined" ? exports :
 (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope) ? self : window));
