//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface ChatServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default UserDTO joinChat(String username)
    {
        return joinChat(username, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default UserDTO joinChat(String username, java.util.Map<String, String> context)
    {
        return _iceI_joinChatAsync(username, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<UserDTO> joinChatAsync(String username)
    {
        return _iceI_joinChatAsync(username, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<UserDTO> joinChatAsync(String username, java.util.Map<String, String> context)
    {
        return _iceI_joinChatAsync(username, context, false);
    }

    /**
     * @hidden
     * @param iceP_username -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<UserDTO> _iceI_joinChatAsync(String iceP_username, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<UserDTO> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "joinChat", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_username);
                 }, istr -> {
                     UserDTO ret;
                     ret = UserDTO.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void leaveChat(String userId)
    {
        leaveChat(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void leaveChat(String userId, java.util.Map<String, String> context)
    {
        _iceI_leaveChatAsync(userId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> leaveChatAsync(String userId)
    {
        return _iceI_leaveChatAsync(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> leaveChatAsync(String userId, java.util.Map<String, String> context)
    {
        return _iceI_leaveChatAsync(userId, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_leaveChatAsync(String iceP_userId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "leaveChat", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                 }, null);
        return f;
    }

    default UserDTO[] getUsers()
    {
        return getUsers(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default UserDTO[] getUsers(java.util.Map<String, String> context)
    {
        return _iceI_getUsersAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<UserDTO[]> getUsersAsync()
    {
        return _iceI_getUsersAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<UserDTO[]> getUsersAsync(java.util.Map<String, String> context)
    {
        return _iceI_getUsersAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<UserDTO[]> _iceI_getUsersAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<UserDTO[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getUsers", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     UserDTO[] ret;
                     ret = UserListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void sendMessage(String userId, String content, MessageTypeEnum type)
    {
        sendMessage(userId, content, type, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendMessage(String userId, String content, MessageTypeEnum type, java.util.Map<String, String> context)
    {
        _iceI_sendMessageAsync(userId, content, type, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendMessageAsync(String userId, String content, MessageTypeEnum type)
    {
        return _iceI_sendMessageAsync(userId, content, type, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendMessageAsync(String userId, String content, MessageTypeEnum type, java.util.Map<String, String> context)
    {
        return _iceI_sendMessageAsync(userId, content, type, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param iceP_content -
     * @param iceP_type -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendMessageAsync(String iceP_userId, String iceP_content, MessageTypeEnum iceP_type, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendMessage", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                     ostr.writeString(iceP_content);
                     MessageTypeEnum.ice_write(ostr, iceP_type);
                 }, null);
        return f;
    }

    default MessageDTO[] getMessages()
    {
        return getMessages(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default MessageDTO[] getMessages(java.util.Map<String, String> context)
    {
        return _iceI_getMessagesAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<MessageDTO[]> getMessagesAsync()
    {
        return _iceI_getMessagesAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<MessageDTO[]> getMessagesAsync(java.util.Map<String, String> context)
    {
        return _iceI_getMessagesAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<MessageDTO[]> _iceI_getMessagesAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<MessageDTO[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getMessages", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     MessageDTO[] ret;
                     ret = MessageListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void sendPrivateMessage(String userId, String targetUserId, String content, MessageTypeEnum type)
    {
        sendPrivateMessage(userId, targetUserId, content, type, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendPrivateMessage(String userId, String targetUserId, String content, MessageTypeEnum type, java.util.Map<String, String> context)
    {
        _iceI_sendPrivateMessageAsync(userId, targetUserId, content, type, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendPrivateMessageAsync(String userId, String targetUserId, String content, MessageTypeEnum type)
    {
        return _iceI_sendPrivateMessageAsync(userId, targetUserId, content, type, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendPrivateMessageAsync(String userId, String targetUserId, String content, MessageTypeEnum type, java.util.Map<String, String> context)
    {
        return _iceI_sendPrivateMessageAsync(userId, targetUserId, content, type, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param iceP_targetUserId -
     * @param iceP_content -
     * @param iceP_type -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendPrivateMessageAsync(String iceP_userId, String iceP_targetUserId, String iceP_content, MessageTypeEnum iceP_type, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendPrivateMessage", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                     ostr.writeString(iceP_targetUserId);
                     ostr.writeString(iceP_content);
                     MessageTypeEnum.ice_write(ostr, iceP_type);
                 }, null);
        return f;
    }

    default MessageDTO[] getPrivateMessages(String userId, String targetUserId)
    {
        return getPrivateMessages(userId, targetUserId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default MessageDTO[] getPrivateMessages(String userId, String targetUserId, java.util.Map<String, String> context)
    {
        return _iceI_getPrivateMessagesAsync(userId, targetUserId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<MessageDTO[]> getPrivateMessagesAsync(String userId, String targetUserId)
    {
        return _iceI_getPrivateMessagesAsync(userId, targetUserId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<MessageDTO[]> getPrivateMessagesAsync(String userId, String targetUserId, java.util.Map<String, String> context)
    {
        return _iceI_getPrivateMessagesAsync(userId, targetUserId, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param iceP_targetUserId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<MessageDTO[]> _iceI_getPrivateMessagesAsync(String iceP_userId, String iceP_targetUserId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<MessageDTO[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getPrivateMessages", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                     ostr.writeString(iceP_targetUserId);
                 }, istr -> {
                     MessageDTO[] ret;
                     ret = MessageListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default GroupDTO createGroup(String groupName, String creatorId)
    {
        return createGroup(groupName, creatorId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default GroupDTO createGroup(String groupName, String creatorId, java.util.Map<String, String> context)
    {
        return _iceI_createGroupAsync(groupName, creatorId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<GroupDTO> createGroupAsync(String groupName, String creatorId)
    {
        return _iceI_createGroupAsync(groupName, creatorId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<GroupDTO> createGroupAsync(String groupName, String creatorId, java.util.Map<String, String> context)
    {
        return _iceI_createGroupAsync(groupName, creatorId, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupName -
     * @param iceP_creatorId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<GroupDTO> _iceI_createGroupAsync(String iceP_groupName, String iceP_creatorId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<GroupDTO> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "createGroup", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupName);
                     ostr.writeString(iceP_creatorId);
                 }, istr -> {
                     GroupDTO ret;
                     ret = GroupDTO.ice_read(istr);
                     return ret;
                 });
        return f;
    }

    default void joinGroup(String groupId, String userId)
    {
        joinGroup(groupId, userId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void joinGroup(String groupId, String userId, java.util.Map<String, String> context)
    {
        _iceI_joinGroupAsync(groupId, userId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> joinGroupAsync(String groupId, String userId)
    {
        return _iceI_joinGroupAsync(groupId, userId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> joinGroupAsync(String groupId, String userId, java.util.Map<String, String> context)
    {
        return _iceI_joinGroupAsync(groupId, userId, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupId -
     * @param iceP_userId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_joinGroupAsync(String iceP_groupId, String iceP_userId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "joinGroup", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_groupId);
                     ostr.writeString(iceP_userId);
                 }, null);
        return f;
    }

    default GroupDTO[] getGroups()
    {
        return getGroups(com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default GroupDTO[] getGroups(java.util.Map<String, String> context)
    {
        return _iceI_getGroupsAsync(context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<GroupDTO[]> getGroupsAsync()
    {
        return _iceI_getGroupsAsync(com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<GroupDTO[]> getGroupsAsync(java.util.Map<String, String> context)
    {
        return _iceI_getGroupsAsync(context, false);
    }

    /**
     * @hidden
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<GroupDTO[]> _iceI_getGroupsAsync(java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<GroupDTO[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getGroups", null, sync, null);
        f.invoke(true, context, null, null, istr -> {
                     GroupDTO[] ret;
                     ret = GroupListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void startVoiceCall(String userId, String targetUserId)
    {
        startVoiceCall(userId, targetUserId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void startVoiceCall(String userId, String targetUserId, java.util.Map<String, String> context)
    {
        _iceI_startVoiceCallAsync(userId, targetUserId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> startVoiceCallAsync(String userId, String targetUserId)
    {
        return _iceI_startVoiceCallAsync(userId, targetUserId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> startVoiceCallAsync(String userId, String targetUserId, java.util.Map<String, String> context)
    {
        return _iceI_startVoiceCallAsync(userId, targetUserId, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param iceP_targetUserId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_startVoiceCallAsync(String iceP_userId, String iceP_targetUserId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "startVoiceCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                     ostr.writeString(iceP_targetUserId);
                 }, null);
        return f;
    }

    default void endVoiceCall(String userId)
    {
        endVoiceCall(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void endVoiceCall(String userId, java.util.Map<String, String> context)
    {
        _iceI_endVoiceCallAsync(userId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> endVoiceCallAsync(String userId)
    {
        return _iceI_endVoiceCallAsync(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> endVoiceCallAsync(String userId, java.util.Map<String, String> context)
    {
        return _iceI_endVoiceCallAsync(userId, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_endVoiceCallAsync(String iceP_userId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "endVoiceCall", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                 }, null);
        return f;
    }

    default void sendGroupMessage(String groupId, String userId, String content, MessageTypeEnum type)
    {
        sendGroupMessage(groupId, userId, content, type, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendGroupMessage(String groupId, String userId, String content, MessageTypeEnum type, java.util.Map<String, String> context)
    {
        _iceI_sendGroupMessageAsync(groupId, userId, content, type, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendGroupMessageAsync(String groupId, String userId, String content, MessageTypeEnum type)
    {
        return _iceI_sendGroupMessageAsync(groupId, userId, content, type, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendGroupMessageAsync(String groupId, String userId, String content, MessageTypeEnum type, java.util.Map<String, String> context)
    {
        return _iceI_sendGroupMessageAsync(groupId, userId, content, type, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupId -
     * @param iceP_userId -
     * @param iceP_content -
     * @param iceP_type -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendGroupMessageAsync(String iceP_groupId, String iceP_userId, String iceP_content, MessageTypeEnum iceP_type, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendGroupMessage", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_groupId);
                     ostr.writeString(iceP_userId);
                     ostr.writeString(iceP_content);
                     MessageTypeEnum.ice_write(ostr, iceP_type);
                 }, null);
        return f;
    }

    default MessageDTO[] getGroupMessages(String groupId)
    {
        return getGroupMessages(groupId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default MessageDTO[] getGroupMessages(String groupId, java.util.Map<String, String> context)
    {
        return _iceI_getGroupMessagesAsync(groupId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<MessageDTO[]> getGroupMessagesAsync(String groupId)
    {
        return _iceI_getGroupMessagesAsync(groupId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<MessageDTO[]> getGroupMessagesAsync(String groupId, java.util.Map<String, String> context)
    {
        return _iceI_getGroupMessagesAsync(groupId, context, false);
    }

    /**
     * @hidden
     * @param iceP_groupId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<MessageDTO[]> _iceI_getGroupMessagesAsync(String iceP_groupId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<MessageDTO[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getGroupMessages", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_groupId);
                 }, istr -> {
                     MessageDTO[] ret;
                     ret = MessageListHelper.read(istr);
                     return ret;
                 });
        return f;
    }

    default void sendVoiceData(String userId, String targetUserId, String audioData)
    {
        sendVoiceData(userId, targetUserId, audioData, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendVoiceData(String userId, String targetUserId, String audioData, java.util.Map<String, String> context)
    {
        _iceI_sendVoiceDataAsync(userId, targetUserId, audioData, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendVoiceDataAsync(String userId, String targetUserId, String audioData)
    {
        return _iceI_sendVoiceDataAsync(userId, targetUserId, audioData, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendVoiceDataAsync(String userId, String targetUserId, String audioData, java.util.Map<String, String> context)
    {
        return _iceI_sendVoiceDataAsync(userId, targetUserId, audioData, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param iceP_targetUserId -
     * @param iceP_audioData -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendVoiceDataAsync(String iceP_userId, String iceP_targetUserId, String iceP_audioData, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendVoiceData", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                     ostr.writeString(iceP_targetUserId);
                     ostr.writeString(iceP_audioData);
                 }, null);
        return f;
    }

    default String getActiveCall(String userId)
    {
        return getActiveCall(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getActiveCall(String userId, java.util.Map<String, String> context)
    {
        return _iceI_getActiveCallAsync(userId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getActiveCallAsync(String userId)
    {
        return _iceI_getActiveCallAsync(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getActiveCallAsync(String userId, java.util.Map<String, String> context)
    {
        return _iceI_getActiveCallAsync(userId, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getActiveCallAsync(String iceP_userId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getActiveCall", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default String getCallAudio(String userId)
    {
        return getCallAudio(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String getCallAudio(String userId, java.util.Map<String, String> context)
    {
        return _iceI_getCallAudioAsync(userId, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getCallAudioAsync(String userId)
    {
        return _iceI_getCallAudioAsync(userId, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> getCallAudioAsync(String userId, java.util.Map<String, String> context)
    {
        return _iceI_getCallAudioAsync(userId, context, false);
    }

    /**
     * @hidden
     * @param iceP_userId -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_getCallAudioAsync(String iceP_userId, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "getCallAudio", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_userId);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ChatServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ChatServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ChatServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ChatServicePrx.class, _ChatServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ChatServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ChatServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ChatServicePrx ice_adapterId(String newAdapterId)
    {
        return (ChatServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ChatServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ChatServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ChatServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ChatServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ChatServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (ChatServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ChatServicePrx ice_connectionCached(boolean newCache)
    {
        return (ChatServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ChatServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ChatServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatServicePrx ice_secure(boolean b)
    {
        return (ChatServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ChatServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ChatServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ChatServicePrx ice_preferSecure(boolean b)
    {
        return (ChatServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ChatServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ChatServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ChatServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ChatServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ChatServicePrx ice_collocationOptimized(boolean b)
    {
        return (ChatServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ChatServicePrx ice_twoway()
    {
        return (ChatServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ChatServicePrx ice_oneway()
    {
        return (ChatServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ChatServicePrx ice_batchOneway()
    {
        return (ChatServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ChatServicePrx ice_datagram()
    {
        return (ChatServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ChatServicePrx ice_batchDatagram()
    {
        return (ChatServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ChatServicePrx ice_compress(boolean co)
    {
        return (ChatServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ChatServicePrx ice_timeout(int t)
    {
        return (ChatServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ChatServicePrx ice_connectionId(String connectionId)
    {
        return (ChatServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ChatServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ChatServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Chat::ChatService";
    }
}
