//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Chat.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Chat;

public interface ChatService extends com.zeroc.Ice.Object
{
    UserDTO joinChat(String username, com.zeroc.Ice.Current current);

    void leaveChat(String userId, com.zeroc.Ice.Current current);

    UserDTO[] getUsers(com.zeroc.Ice.Current current);

    void sendMessage(String userId, String content, MessageTypeEnum type, com.zeroc.Ice.Current current);

    MessageDTO[] getMessages(com.zeroc.Ice.Current current);

    void sendPrivateMessage(String userId, String targetUserId, String content, MessageTypeEnum type, com.zeroc.Ice.Current current);

    MessageDTO[] getPrivateMessages(String userId, String targetUserId, com.zeroc.Ice.Current current);

    GroupDTO createGroup(String groupName, String creatorId, com.zeroc.Ice.Current current);

    void joinGroup(String groupId, String userId, com.zeroc.Ice.Current current);

    GroupDTO[] getGroups(com.zeroc.Ice.Current current);

    void startVoiceCall(String userId, String targetUserId, com.zeroc.Ice.Current current);

    void endVoiceCall(String userId, com.zeroc.Ice.Current current);

    /** @hidden */
    static final String[] _iceIds =
    {
        "::Chat::ChatService",
        "::Ice::Object"
    };

    @Override
    default String[] ice_ids(com.zeroc.Ice.Current current)
    {
        return _iceIds;
    }

    @Override
    default String ice_id(com.zeroc.Ice.Current current)
    {
        return ice_staticId();
    }

    static String ice_staticId()
    {
        return "::Chat::ChatService";
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_joinChat(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_username;
        iceP_username = istr.readString();
        inS.endReadParams();
        UserDTO ret = obj.joinChat(iceP_username, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        UserDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_leaveChat(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        iceP_userId = istr.readString();
        inS.endReadParams();
        obj.leaveChat(iceP_userId, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getUsers(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        UserDTO[] ret = obj.getUsers(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        UserListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendMessage(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        String iceP_content;
        MessageTypeEnum iceP_type;
        iceP_userId = istr.readString();
        iceP_content = istr.readString();
        iceP_type = MessageTypeEnum.ice_read(istr);
        inS.endReadParams();
        obj.sendMessage(iceP_userId, iceP_content, iceP_type, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getMessages(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        MessageDTO[] ret = obj.getMessages(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        MessageListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_sendPrivateMessage(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        String iceP_targetUserId;
        String iceP_content;
        MessageTypeEnum iceP_type;
        iceP_userId = istr.readString();
        iceP_targetUserId = istr.readString();
        iceP_content = istr.readString();
        iceP_type = MessageTypeEnum.ice_read(istr);
        inS.endReadParams();
        obj.sendPrivateMessage(iceP_userId, iceP_targetUserId, iceP_content, iceP_type, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getPrivateMessages(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        String iceP_targetUserId;
        iceP_userId = istr.readString();
        iceP_targetUserId = istr.readString();
        inS.endReadParams();
        MessageDTO[] ret = obj.getPrivateMessages(iceP_userId, iceP_targetUserId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        MessageListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_createGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupName;
        String iceP_creatorId;
        iceP_groupName = istr.readString();
        iceP_creatorId = istr.readString();
        inS.endReadParams();
        GroupDTO ret = obj.createGroup(iceP_groupName, iceP_creatorId, current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        GroupDTO.ice_write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_joinGroup(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_groupId;
        String iceP_userId;
        iceP_groupId = istr.readString();
        iceP_userId = istr.readString();
        inS.endReadParams();
        obj.joinGroup(iceP_groupId, iceP_userId, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_getGroups(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        inS.readEmptyParams();
        GroupDTO[] ret = obj.getGroups(current);
        com.zeroc.Ice.OutputStream ostr = inS.startWriteParams();
        GroupListHelper.write(ostr, ret);
        inS.endWriteParams(ostr);
        return inS.setResult(ostr);
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_startVoiceCall(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        String iceP_targetUserId;
        iceP_userId = istr.readString();
        iceP_targetUserId = istr.readString();
        inS.endReadParams();
        obj.startVoiceCall(iceP_userId, iceP_targetUserId, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /**
     * @hidden
     * @param obj -
     * @param inS -
     * @param current -
     * @return -
    **/
    static java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceD_endVoiceCall(ChatService obj, final com.zeroc.IceInternal.Incoming inS, com.zeroc.Ice.Current current)
    {
        com.zeroc.Ice.Object._iceCheckMode(null, current.mode);
        com.zeroc.Ice.InputStream istr = inS.startReadParams();
        String iceP_userId;
        iceP_userId = istr.readString();
        inS.endReadParams();
        obj.endVoiceCall(iceP_userId, current);
        return inS.setResult(inS.writeEmptyParams());
    }

    /** @hidden */
    final static String[] _iceOps =
    {
        "createGroup",
        "endVoiceCall",
        "getGroups",
        "getMessages",
        "getPrivateMessages",
        "getUsers",
        "ice_id",
        "ice_ids",
        "ice_isA",
        "ice_ping",
        "joinChat",
        "joinGroup",
        "leaveChat",
        "sendMessage",
        "sendPrivateMessage",
        "startVoiceCall"
    };

    /** @hidden */
    @Override
    default java.util.concurrent.CompletionStage<com.zeroc.Ice.OutputStream> _iceDispatch(com.zeroc.IceInternal.Incoming in, com.zeroc.Ice.Current current)
        throws com.zeroc.Ice.UserException
    {
        int pos = java.util.Arrays.binarySearch(_iceOps, current.operation);
        if(pos < 0)
        {
            throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
        }

        switch(pos)
        {
            case 0:
            {
                return _iceD_createGroup(this, in, current);
            }
            case 1:
            {
                return _iceD_endVoiceCall(this, in, current);
            }
            case 2:
            {
                return _iceD_getGroups(this, in, current);
            }
            case 3:
            {
                return _iceD_getMessages(this, in, current);
            }
            case 4:
            {
                return _iceD_getPrivateMessages(this, in, current);
            }
            case 5:
            {
                return _iceD_getUsers(this, in, current);
            }
            case 6:
            {
                return com.zeroc.Ice.Object._iceD_ice_id(this, in, current);
            }
            case 7:
            {
                return com.zeroc.Ice.Object._iceD_ice_ids(this, in, current);
            }
            case 8:
            {
                return com.zeroc.Ice.Object._iceD_ice_isA(this, in, current);
            }
            case 9:
            {
                return com.zeroc.Ice.Object._iceD_ice_ping(this, in, current);
            }
            case 10:
            {
                return _iceD_joinChat(this, in, current);
            }
            case 11:
            {
                return _iceD_joinGroup(this, in, current);
            }
            case 12:
            {
                return _iceD_leaveChat(this, in, current);
            }
            case 13:
            {
                return _iceD_sendMessage(this, in, current);
            }
            case 14:
            {
                return _iceD_sendPrivateMessage(this, in, current);
            }
            case 15:
            {
                return _iceD_startVoiceCall(this, in, current);
            }
        }

        assert(false);
        throw new com.zeroc.Ice.OperationNotExistException(current.id, current.facet, current.operation);
    }
}
